prueba
oconsl/fs-plus-2023-c9 pull request #10
Opened 2023-04-04 23:14 UTC by fxcx

hola

2023-04-06 23:23 UTC, gonzalez-gabriel commented on students/example.md
> +### Facundo BURGOS
No debes modificar el archivo `example.md` debes crear un nuevo archivo con el formato `apellido-nombre.md` y en ese archivo escribir esto que pusiste aquí

2023-04-06 23:26 UTC, gonzalez-gabriel commented on students/example.md
>  > Respuesta aquí
Ya sea aquí (en el archivo nuevo que debes crear) o en la descripción del PR debes indicar cuales pasos de todo el proceso recordabas y cuales tuviste que verlos nuevamente

2023-04-06 23:26 UTC, gonzalez-gabriel requested changes
Hay correcciones que realizar 😁

2023-04-10 23:24 UTC, fxcx commented on students/example.md
> +### Facundo BURGOS
hola ahi creo que lo correji

2023-04-10 23:27 UTC, fxcx commented
cree un archivo texto y puse mi nombre y apellido no sabia si tenia que crear uno nuevo o editarlo

2023-04-11 00:47 UTC, gonzalez-gabriel requested changes
Hay cambios que realizar:
- El nombre del archivo debe tener el formato `apellido-nombre.md` no `texto.md`

2023-04-26 21:22 UTC, closed without merging